config/routes.rb
Xen::Application.routes.draw do

  resources :reports

  resources :tasks

  
    namespace :api do
      get "/host" => "api#host"      
      post "/host/add" => "api#host_add"
      post "/host/delete" => "api#host_delete"
      post "/host/update" => "api#host_update"

      post "/xenhost" => "api#xenhost"
      get "/xenhost/pbd" => "api#xenhost_pbd"
      get "/xenhost/sr" => "api#xenhost_sr"
      post "/xenhost/detail" => "api#xenhost_detail"

      get "/xenserver" => "api#xenserver"
      post "/xenserver" => "api#xenserver_pool"
      post "/xenserver/get" => "api#xenserver_get"
      post "/xenserver/start" => "api#xenserver_start"
      post "/xenserver/stop" => "api#xenserver_stop"
      post "/xenserver/destroy" => "api#xenserver_destroy"
      post "/xenserver/hard_reboot" => "api#xenserver_hard_reboot"
      post "/xenserver/brutal_shutdown" => "api#xenserver_brutal_shutdown"

      post "/provision/xenserver" => "api#provision_xenserver"
      post "/provision/async_xenservers" => "api#provision_async_xenservers"
      post "/provision/async_destroy_xenservers" => "api#provision_async_destroy_xenservers"
      post "/provision/cache_template" => "api#provision_cache_template"
      post "/provision/new_provision_task" => "api#provision_new_provision_task"
      post "/provision/run_task" => "api#provision_run_task"

      get "/template/all" => "api#template_all"
      post "/template" => "api#template"
      post "/template/base" => "api#template_base"
      get "/snapshot" => "api#snapshot"
      

      match "/pool" => "api#pool", :via => [:get, :post]
      get "/pool/inspect" => "api#pool_inspect"
      post "/pool/update" => "api#pool_update"

      get "/sr" => "api#sr"
      post "/sr/provision" => "api#sr_provision"
      get "/pif" => "api#pif"
      get "/pbd" => "api#pbd"
      post "/pbd/provision" => "api#pbd_provision"

      get "/clusters" => "api#clusters"
      post "/clusters/new" => "api#new_clusters"
      post "/clusters/update" => "api#update_clusters"
      post "/clusters/delete" => "api#delete_clusters"
      post "/clusters/member" => "api#member_clusters"

      
      post "/perf/xenhost" => "api#perf_xenhost"
      post "/perf/xenserver" => "api#perf_xenserver"

      post "/report/xenhost/all/excel" => "api#report_xenhost_all_excel"
      post "/report/xenhost/all" => "api#report_xenhost_all"
      post "/report/xenhost" => "api#report_xenhost"

      get "/dhcp" => "api#dhcp"
      post "/dhcp/scan_ip" => "api#dhcp_scan_ip"
      get "/dhcp/stop" => "api#dhcp_stop"
      get "/dhcp/start" => "api#dhcp_start"
      get "/dhcp/restart" => "api#dhcp_restart"

      get "/task" => "api#task"
      post "/task/subtask" => "api#task_subtask"
      post "/task/status" => "api#task_status"
      post "/task/run" => "api#task_run"
      post "/task/run_assign" => "api#task_run_assign"
      post "/task/delete" => "api#task_delete"

  
      get "/xen/all" => "api#xen_all"
      

      get "/ad/ou" => "ad#ad_ou"
      get "/ad/user" => "ad#ad_user"
      get "/ad/ou/user" => "ad#ad_ou_user"
      get "/ad/ou/computer" => "ad#ad_ou_computer"
      get "/ad/computer" => "ad#ad_computer"
      get "/ad/computer/add" => "ad#ad_computer_add"
      get "/ad/computer/remove" => "ad#ad_computer_remove"

      get "/desktop/machine_catalog/add_machine" => "desktop#machine_catalog_add_machine"
      get "/desktop/machine_catalog/remove_machine" => "desktop#machine_catalog_remove_machine"
      get "/desktop/machine_catalog" => "desktop#machine_catalog"
      get "/desktop/delivery_group" => "desktop#delivery_group"
      get "/desktop/xenserver" => "desktop#xenserver"
      get "/desktop/hypervisor_connection" => "desktop#hypervisor_connection"
      post "/desktop/do_assign" => "desktop#do_assign"
      post "/desktop/do_unassign" => "desktop#do_unassign"

      get "/user" => "api#user"
      post "/user/update" => "api#user_update"
      post "/user/delete" => "api#user_delete"

      post "/config" => "api#config"
      post "/config/update" => "api#config_update"

      get "/test" => "api#test"
      get "/test2" => "api#test2"
      get "/test3" => "api#test3"
      get "/test4" => "api#test4"
      get "/test5" => "api#test5"

      post "/login" => "sessions#simple_login"
    end

    root :to => 'home#index'

  

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :runner %><br>
    <%= f.text_field :runner %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_area :msg %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.date_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br>
    <%= f.date_select :started_at %>
  </div>
  <div class="field">
    <%= f.label :finished_at %><br>
    <%= f.date_select :finished_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Runner</th>
      <th>Result</th>
      <th>Msg</th>
      <th>Created at</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.task_id %></td>
        <td><%= report.runner %></td>
        <td><%= report.result %></td>
        <td><%= report.msg %></td>
        <td><%= report.created_at %></td>
        <td><%= report.started_at %></td>
        <td><%= report.finished_at %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @report.task_id %>
</p>

<p>
  <strong>Runner:</strong>
  <%= @report.runner %>
</p>

<p>
  <strong>Result:</strong>
  <%= @report.result %>
</p>

<p>
  <strong>Msg:</strong>
  <%= @report.msg %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @report.created_at %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @report.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @report.finished_at %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>